/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CvController.java
 *
 * Created on 2011/11/30, 19:51:53
 */
package org.ubilab.cicp2011.cv;

/**
 * 位置推定処理のコントローラウインドウ
 * @author atsushi-o
 * @since 2011/11/30
 */
public class CvController extends javax.swing.JFrame {
    private static final CvController instance;
    private CvControllerDelegate delegate;
    
    static {
        instance = new CvController();
    }

    /** Creates new form CvController */
    private CvController() {
        initComponents();
    }
    
    /**
     * CvControllerのインスタンスを返す
     * @return CvControllerのインスタンス
     */
    public static CvController getInstance() {
        return instance;
    }
    
    /**
     * デリゲートクラスを設定する
     * @param delegate デリゲートクラス
     * @since 2011/11/30
     */
    public void setDelegate(CvControllerDelegate delegate) {
        this.delegate = delegate;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("CvController");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                controllerClosing(evt);
            }
        });

        jButton1.setText("Capture");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jToggleButton1.setText("OFF");
        jToggleButton1.setName("Source"); // NOI18N
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                windowToggle(evt);
            }
        });

        jToggleButton2.setText("OFF");
        jToggleButton2.setName("Hough"); // NOI18N
        jToggleButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                windowToggle(evt);
            }
        });

        jToggleButton3.setText("OFF");
        jToggleButton3.setActionCommand("ROI");
        jToggleButton3.setName("ROI"); // NOI18N
        jToggleButton3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                windowToggle(evt);
            }
        });

        jLabel1.setText("Source:");

        jLabel2.setText("Hough:");

        jLabel3.setText("ROI:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton3)
                    .addComponent(jLabel1)
                    .addComponent(jToggleButton1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jToggleButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * テキストエリアの文を更新する
     * @param str 表示する文
     * @since 2011/11/30
     */
    public void updateText(String str) {
        jTextArea1.setText(str);
    }
    /**
     * テキストエリアに文を追記する
     * @param str 追記する文
     * @since 2011/12/01
     */
    public void addText(String str) {
        jTextArea1.append(str);
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }
    /**
     * テキストエリアの文を改行する
     * @since 2011/12/01
     */
    public void newLineText() {
        // 改行コード取得
        String nl = System.getProperty("line.separator");
        
        addText(nl);
    }
    /**
     * テキストエリアを初期化する
     * @since 2011/12/01
     */
    public void clearText() {
        jTextArea1.setText("");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (delegate != null) delegate.capture();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (delegate != null) delegate.quit();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void controllerClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_controllerClosing
        if (delegate != null) delegate.quit();
    }//GEN-LAST:event_controllerClosing

    private void windowToggle(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_windowToggle
        if (delegate != null) {
            // イベント取得
            javax.swing.JToggleButton btn = (javax.swing.JToggleButton)evt.getSource();
            delegate.setVisible(btn.getName(), btn.isSelected());
            btn.setText(btn.isSelected()?"ON":"OFF");
        }
    }//GEN-LAST:event_windowToggle

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
