/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CvController.java
 *
 * Created on 2011/11/30, 19:51:53
 */
package org.ubilab.cicp2011.cv;

/**
 * 位置推定処理のコントローラウインドウ
 * @author atsushi-o
 * @since 2011/11/30
 */
public class CvController extends javax.swing.JFrame {
    private static final CvController instance;
    private CvControllerDelegate delegate;
    
    static {
        instance = new CvController();
    }

    /** Creates new form CvController */
    private CvController() {
        initComponents();
    }
    
    /**
     * CvControllerのインスタンスを返す
     * @return CvControllerのインスタンス
     */
    public static CvController getInstance() {
        return instance;
    }
    
    /**
     * デリゲートクラスを設定する
     * @param delegate デリゲートクラス
     * @since 2011/11/30
     */
    public void setDelegate(CvControllerDelegate delegate) {
        this.delegate = delegate;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("CvController");
        setResizable(false);

        jButton1.setText("Capture");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * テキストエリアの文を更新する
     * @param str 表示する文
     * @since 2011/11/30
     */
    public void updateText(String str) {
        jTextArea1.setText(str);
    }
    /**
     * テキストエリアに文を追記する
     * @param str 追記する文
     * @since 2011/12/01
     */
    public void addText(String str) {
        StringBuilder sb = new StringBuilder(jTextArea1.getText());
        sb.append(str);
        
        jTextArea1.setText(sb.toString());
    }
    /**
     * テキストエリアの文を改行する
     * @since 2011/12/01
     */
    public void newLineText() {
        // 改行コード取得
        String nl = System.getProperty("line.separator");
        
        addText(nl);
    }
    /**
     * テキストエリアを初期化する
     * @since 2011/12/01
     */
    public void clearText() {
        jTextArea1.setText("");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (delegate != null) delegate.capture();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (delegate != null) delegate.quit();
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
